project-includes = [
    ".",
    "**/*.py"
]

project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/venv/**/*",
]

site-package-path = [
    "c:/Users/RARITY/Desktop/Soccer Goal Predictor/backend/venv/Lib/site-packages",
    "venv/Lib/site-packages"
]

search-paths = [
    "c:/Users/RARITY/Desktop/Soccer Goal Predictor/backend",
    "."
]

[errors]
missing-import = "ignore"
bad-override = "ignore"
invalid-variance = "ignore"
