import React, { useState, useEffect } from 'react';
import { Zap, X, Copy, Check, ShieldCheck, Flame, TrendingUp, RefreshCw } from 'lucide-react';

export default function AccumulatorModal({ isOpen, onClose, apiRequest, selectedPickDay, darkMode }) {
  const [accumulators, setAccumulators] = useState(null);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('safe_double'); // 'safe_double' | 'over_1_5_5fold' | 'high_yield_3fold'
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (isOpen) {
      fetchAccas();
    }
  }, [isOpen, selectedPickDay]);

  const fetchAccas = async () => {
    setLoading(true);
    try {
      const res = await apiRequest('get', `/api/accumulators/generate?day=${selectedPickDay || 'ALL_DAYS'}`);
      if (res.data?.status === 'ok') {
        setAccumulators(res.data.accumulators);
      }
    } catch (err) {
      console.error('Error fetching accumulators:', err);
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  const currentAcca = accumulators ? accumulators[activeTab] : null;

  const copySlipToClipboard = () => {
    if (!currentAcca || !currentAcca.legs) return;
    const textLines = [
      `⚡ SOCCER GOAL PREDICTOR ACCUMULATOR SLIP ⚡`,
      `Mode: ${activeTab.replace(/_/g, ' ').toUpperCase()}`,
      `Total Combined Odds: ${currentAcca.total_odds}x | Probability: ${currentAcca.combined_probability}%\n`,
      ...currentAcca.legs.map((leg, idx) => 
        `${idx + 1}. ${leg.home_team} vs ${leg.away_team}\n   Pick: ${leg.market} (${leg.probability}% | Odds: ${leg.implied_odds})`
      ),
      `\nGenerated by Dixon-Coles Predictive Engine`
    ];
    navigator.clipboard.writeText(textLines.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/80 backdrop-blur-md animate-fadeIn">
      <div className={`w-full max-w-3xl rounded-3xl border shadow-2xl overflow-hidden flex flex-col max-h-[90vh] transition-colors ${
        darkMode ? 'bg-slate-900 border-slate-800 text-white' : 'bg-white border-slate-200 text-slate-900'
      }`}>
        
        {/* Header */}
        <div className="p-4 sm:p-6 border-b border-slate-800 flex items-center justify-between bg-gradient-to-r from-emerald-900/30 via-slate-900 to-cyan-900/30">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-2xl bg-emerald-500/20 text-emerald-400 border border-emerald-500/40">
              <Zap className="w-6 h-6 animate-pulse" />
            </div>
            <div>
              <h2 className="text-lg sm:text-xl font-black tracking-tight">Smart Accumulator Generator</h2>
              <p className="text-xs text-slate-400">Cross-league diversified betting slips optimized for high hit rates</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Acca Type Tabs */}
        <div className="p-3 sm:p-4 border-b border-slate-800/80 bg-slate-950/40 flex items-center gap-2 overflow-x-auto custom-scrollbar">
          <button
            onClick={() => setActiveTab('safe_double')}
            className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all whitespace-nowrap ${
              activeTab === 'safe_double'
                ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-600/20'
                : 'bg-slate-800/60 text-slate-400 hover:text-white'
            }`}
          >
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Safe Double (2-Fold)</span>
          </button>

          <button
            onClick={() => setActiveTab('over_1_5_5fold')}
            className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all whitespace-nowrap ${
              activeTab === 'over_1_5_5fold'
                ? 'bg-cyan-600 text-white shadow-lg shadow-cyan-600/20'
                : 'bg-slate-800/60 text-slate-400 hover:text-white'
            }`}
          >
            <Flame className="w-4 h-4 text-cyan-400" />
            <span>Over 1.5 5-Fold</span>
          </button>

          <button
            onClick={() => setActiveTab('high_yield_3fold')}
            className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all whitespace-nowrap ${
              activeTab === 'high_yield_3fold'
                ? 'bg-amber-600 text-white shadow-lg shadow-amber-600/20'
                : 'bg-slate-800/60 text-slate-400 hover:text-white'
            }`}
          >
            <TrendingUp className="w-4 h-4 text-amber-400" />
            <span>High Yield 3-Fold</span>
          </button>

          <button
            onClick={fetchAccas}
            disabled={loading}
            className="ml-auto p-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 transition-all shrink-0"
            title="Refresh Accumulator Candidates"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>
        </div>

        {/* Content Body */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-4">
          {loading ? (
            <div className="py-12 text-center space-y-3">
              <RefreshCw className="w-8 h-8 text-emerald-400 animate-spin mx-auto" />
              <p className="text-sm font-semibold text-slate-400">Analyzing cross-league correlations & generating optimal slip...</p>
            </div>
          ) : currentAcca && currentAcca.legs && currentAcca.legs.length > 0 ? (
            <div className="space-y-4">
              
              {/* Slip Summary Header */}
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 p-4 rounded-2xl bg-slate-950/80 border border-slate-800">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Total Legs</span>
                  <span className="text-lg font-black text-white block mt-0.5">{currentAcca.legs_count} Matches</span>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Est. Implied Odds</span>
                  <span className="text-lg font-black text-emerald-400 block mt-0.5">{currentAcca.total_odds}x</span>
                </div>
                <div className="col-span-2 sm:col-span-1">
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Combined Model Prob</span>
                  <span className="text-lg font-black text-cyan-400 block mt-0.5">{currentAcca.combined_probability}%</span>
                </div>
              </div>

              {/* Legs Table */}
              <div className="space-y-2.5">
                {currentAcca.legs.map((leg, i) => (
                  <div key={i} className="p-3.5 rounded-2xl bg-slate-950/40 border border-slate-800/80 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
                    <div className="space-y-0.5">
                      <div className="flex items-center gap-2">
                        <span className="w-5 h-5 rounded-full bg-emerald-500/20 text-emerald-400 text-[10px] font-black flex items-center justify-center border border-emerald-500/40">
                          {i + 1}
                        </span>
                        <span className="text-xs font-extrabold text-white">{leg.match}</span>
                      </div>
                      <p className="text-[11px] text-slate-400 pl-7">{leg.league} • Exp. Goals: {leg.expected_goals} • Scoreline: {leg.most_likely_score}</p>
                    </div>

                    <div className="flex items-center gap-3 self-end sm:self-center pl-7 sm:pl-0">
                      <div className="text-right">
                        <span className="text-xs font-black text-emerald-400 block">{leg.market}</span>
                        <span className="text-[10px] font-semibold text-slate-400">{leg.probability}% Prob ({leg.implied_odds} Odds)</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="py-12 text-center space-y-2">
              <p className="text-sm font-bold text-slate-300">Insufficient match candidates for this accumulator mode.</p>
              <p className="text-xs text-slate-500">Try selecting "All Match Days" or switching to another accumulator mode.</p>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/60 flex items-center justify-between">
          <p className="text-[11px] text-slate-500">Always gamble responsibly.</p>
          <button
            onClick={copySlipToClipboard}
            disabled={!currentAcca || !currentAcca.legs || currentAcca.legs.length === 0}
            className="px-5 py-2.5 rounded-xl text-xs font-extrabold bg-emerald-600 hover:bg-emerald-500 text-white transition-all shadow-lg shadow-emerald-600/20 flex items-center gap-2 disabled:opacity-50"
          >
            {copied ? <Check className="w-4 h-4 text-white" /> : <Copy className="w-4 h-4 text-white" />}
            <span>{copied ? 'Copied Slip to Clipboard!' : 'Copy Acca Slip'}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
